// This file is automatically generated -- do not try to change it.
// The YAMAS license applies.

#include "boost/tuple/tuple.hpp"
#include <string> 
#include <map> 
// yamas version tuple: major, minor, bug fix 
typedef boost::tuple<int, int, int> version;
#ifdef __GNUC__ 
  typedef boost::tuple<int, int, int> gcc_version;
#endif

namespace yamas {
     const version VERSION(1,4,3);
     const std::string DATE(" 28. Aug 2015");
     const std::string REVISION("");
     #ifdef __GNUC__ 
      const gcc_version GCC_VERSION(__GNUC__,__GNUC_MINOR__,__GNUC_PATCHLEVEL__);
     #endif 
} // end namespace yamas
